services:
  - type: web
    name: pricemymeds-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true  # Render will generate a secure random value
      - key: PORT
        value: 10000  # Render's default port